### ISSUE TITLE
Tienes pantallazos

### ISSUE THREAD

**Issue by johnfelipe** [demianfe/parlamentoabiertopy#1]
Tienes url o pantallazos de ejemplo

**Comment by demianfe** [comment]
Lo que este proyecto tiene actualmente es: los scripts de instalacion de las plataformas, utilizando docker(https://www.docker.com/), además de un scrapper que extrae datos de los sitios web http://silpy.congreso.gov.py/,  http://www.senado.gov.py/ y http://www.diputados.gov.py/ww2/.
